# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kv_cache.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'kv_cache.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ekv_cache.proto\x12\x08kv_cache\"\xb8\x01\n\x07KVLayer\x12\x10\n\x08layer_id\x18\x01 \x01(\x05\x12\x11\n\tnum_heads\x18\x02 \x01(\x05\x12\x10\n\x08head_dim\x18\x03 \x01(\x05\x12\x0f\n\x07seq_len\x18\x04 \x01(\x05\x12\r\n\x05\x64type\x18\x05 \x01(\t\x12\x10\n\x08key_data\x18\x06 \x01(\x0c\x12\x12\n\nvalue_data\x18\x07 \x01(\x0c\x12\x16\n\x0e\x64\x65lta_mem_incr\x18\x08 \x01(\x0c\x12\x18\n\x10mem_decay_factor\x18\t \x01(\x02\"\xaf\x01\n\tModelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08n_layers\x18\x02 \x01(\x05\x12\x0f\n\x07n_heads\x18\x03 \x01(\x05\x12\x10\n\x08head_dim\x18\x04 \x01(\x05\x12\x10\n\x08\x63tx_size\x18\x05 \x01(\x05\x12\x14\n\x0cis_llama_cpp\x18\x06 \x01(\x08\x12\x0f\n\x07is_vllm\x18\x07 \x01(\x08\x12\x0f\n\x07use_kda\x18\x08 \x01(\x08\x12\x15\n\ruse_delta_mem\x18\t \x01(\x08\"\x97\x01\n\x07KVState\x12\'\n\nmodel_info\x18\x01 \x01(\x0b\x32\x13.kv_cache.ModelInfo\x12!\n\x06layers\x18\x02 \x03(\x0b\x32\x11.kv_cache.KVLayer\x12\x17\n\x0f\x63onsumed_tokens\x18\x03 \x01(\x05\x12\x0e\n\x06\x64\x65vice\x18\x04 \x01(\t\x12\x17\n\x0fmem_update_rate\x18\x05 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kv_cache_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KVLAYER']._serialized_start=29
  _globals['_KVLAYER']._serialized_end=213
  _globals['_MODELINFO']._serialized_start=216
  _globals['_MODELINFO']._serialized_end=391
  _globals['_KVSTATE']._serialized_start=394
  _globals['_KVSTATE']._serialized_end=545
# @@protoc_insertion_point(module_scope)
