"""Auto-generated by MTPHeadIRCompiler from IR v1.0."""
import torch
import torch.nn as nn
import torch.nn.functional as F
from dataclasses import dataclass

@dataclass
class MTPHeadConfig:
    hidden_size: int = 2048
    vocab_size: int = 151936
    num_heads: int = 16
    head_dim: int = 128
    intermediate_size: int = 5632
    rms_norm_eps: float = 1e-06

class MTPRMSNorm(nn.Module):
    def __init__(self, dim, eps=1e-06):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(dim))
        self.eps = eps
    def forward(self, x):
        x32 = x.float()
        var = x32.pow(2).mean(-1, keepdim=True)
        return (self.weight * (x32 * torch.rsqrt(var + self.eps))).to(x.dtype)

class MTPAttention(nn.Module):
    def __init__(self, hidden_size=2048, num_heads=16, head_dim=128):
        super().__init__()
        self.num_heads = num_heads
        self.head_dim = head_dim
        self.scale = head_dim ** -0.5
        inner = num_heads * head_dim
        self.q_proj = nn.Linear(hidden_size, inner, bias=False)
        self.k_proj = nn.Linear(hidden_size, inner, bias=False)
        self.v_proj = nn.Linear(hidden_size, inner, bias=False)
        self.o_proj = nn.Linear(inner, hidden_size, bias=False)
    def forward(self, x):
        B, T, _ = x.shape
        q = self.q_proj(x).reshape(B, T, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).reshape(B, T, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).reshape(B, T, self.num_heads, self.head_dim).transpose(1, 2)
        attn = torch.softmax((q @ k.transpose(-2, -1)) * self.scale, dim=-1)
        out = (attn @ v).transpose(1, 2).reshape(B, T, -1)
        return self.o_proj(out)

class MTPMLP(nn.Module):
    def __init__(self, hidden_size=2048, intermediate_size=5632):
        super().__init__()
        self.gate_proj = nn.Linear(hidden_size, intermediate_size, bias=False)
        self.up_proj = nn.Linear(hidden_size, intermediate_size, bias=False)
        self.down_proj = nn.Linear(intermediate_size, hidden_size, bias=False)
    def forward(self, x):
        return self.down_proj(F.silu(self.gate_proj(x)) * self.up_proj(x))

class MTPHead(nn.Module):
    def __init__(self, config=None):
        super().__init__()
        config = config or MTPHeadConfig()
        self.proj = nn.Linear(config.hidden_size * 2, config.hidden_size, bias=False)
        self.norm1 = MTPRMSNorm(config.hidden_size, config.rms_norm_eps)
        self.attn = MTPAttention(config.hidden_size, config.num_heads, config.head_dim)
        self.norm2 = MTPRMSNorm(config.hidden_size, config.rms_norm_eps)
        self.mlp = MTPMLP(config.hidden_size, config.intermediate_size)
        self.norm_out = MTPRMSNorm(config.hidden_size, config.rms_norm_eps)
        self._shared_lm_head = None
    def set_shared_lm_head(self, w):
        self._shared_lm_head = w
    def forward(self, hidden_states, token_embedding):
        x = torch.cat([hidden_states, token_embedding], dim=-1)
        x = self.proj(x)
        x = self.norm1(x)
        x = x + self.attn(x)
        x = self.norm2(x)
        x = x + self.mlp(x)
        x = self.norm_out(x)
        if self._shared_lm_head is not None:
            return F.linear(x, self._shared_lm_head)
        return x
