#!/bin/bash
# check_build_tracked.sh — pre-commit 檢查：build/bin 的 dylib 與 rpath 是否被 git 追蹤
#
# 背景（見 docs/檢討報告_2026-08-26_git與build追蹤疏失.md）：
#   疏失 B: 版本化 dylib（libllama.0.0.15 等）被 .gitignore 的 /build* 一刀切忽略
#            → git 完全看不到、rebuild 一覆寫就永久遺失（29.85 t/s build 一度救不回來）
#   疏失 D: exe 的 @rpath 被改到別的 build 目錄 / symlink 指到不相容 dylib
#            → production 載入錯誤 dylib，batch cap / garbled output
# 本 script 在每次 commit 前自動驗證這兩個洞沒有再發生：
#   1. build/bin 裡每個 *.dylib、必要 dylib 前綴、關鍵 exe 都必須被 git 追蹤（不得 untracked / 被忽略）
#   2. symlink（如 libllama.0.dylib）必須解析到「已追蹤」的目標
#   3. 關鍵 exe 的 @rpath 必須指向本 repo 自己的 build/bin（不得被改到別處）
#
# 檢查 6（2026-08-30 新增）：main⊆dev 分支包含性
#   「main 有的 dev 都要有」— 在 dev 上 commit 時，本地 main 與 github0823/main
#   必須已是 HEAD 的祖先；在 main 上直接 commit 會使 main 領先 dev → 擋下。
#   修復方式：git merge main（在 dev 上）整合後再 commit；晉升一律走
#   git switch main && git merge --ff-only dev（fast-forward 不觸發本 hook）。
#
# 用法：
#   scripts/check_build_tracked.sh                 # 檢查目前 cwd 所在的 repo
#   scripts/check_build_tracked.sh --repo PATH     # 檢查指定 repo
#   scripts/check_build_tracked.sh --install-hook  # 安裝到 .git/hooks/pre-commit（每次 commit 自動跑）
#   scripts/check_build_tracked.sh --list-rpaths   # 只列出關鍵 exe 的 @rpath（快速診斷）
#
# env：
#   BIN_DIR          build 目錄相對路徑（預設 build/bin）
#   REQUIRED_EXES    空白分隔的 exe 清單（預設 "llama-simple llama-speculative-simple llama-bench"）
#   REQUIRED_DYLIB   空白分隔的 dylib 前綴（預設 "libllama. libllama-common. libmtmd. libggml."）
#   ALLOW_MISSING=1  允許 build/bin 或檔案不存在（不擋 commit；預設為擋）

set -uo pipefail

REPO_ROOT=""
INSTALL_HOOK=0
LIST_RPATHS=0
HOOK_BIN_DIR=""
BIN_DIR="${BIN_DIR:-build/bin}"
REQUIRED_EXES=(${REQUIRED_EXES:-llama-simple llama-speculative-simple llama-bench})
REQUIRED_DYLIB=(${REQUIRED_DYLIB:-libllama. libllama-common. libmtmd. libggml.})

usage() {
    sed -n '2,40p' "$0" | sed 's/^# \{0,1\}//'
    exit 2
}

while [ $# -gt 0 ]; do
    case "$1" in
        --repo) REPO_ROOT="$2"; shift 2 ;;
        --install-hook)
            INSTALL_HOOK=1; shift
            # 可選擇性接 BIN_DIR：--install-hook src/llama.cpp/build/bin
            case "${1:-}" in ''|--*) : ;; *) HOOK_BIN_DIR="$1"; shift ;; esac
            ;;
        --list-rpaths) LIST_RPATHS=1; shift ;;
        -h|--help) usage ;;
        *) usage ;;
    esac
done

if [ -z "$REPO_ROOT" ]; then
    REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "error: not inside a git repo（用 --repo PATH 指定）"; exit 2; }
fi
# 真正 repo root：.git 可能在上層（如 llama.cpp-master 只是 llama-src repo 的子目錄）
REPO_ROOT="$(git -C "$REPO_ROOT" rev-parse --show-toplevel 2>/dev/null || echo "$REPO_ROOT")"
REPO_ROOT="$(cd "$REPO_ROOT" && pwd -P)" || { echo "error: repo 不存在: $REPO_ROOT"; exit 2; }
GIT_DIR="$(git -C "$REPO_ROOT" rev-parse --absolute-git-dir 2>/dev/null)"
BIN_ABS="$REPO_ROOT/$BIN_DIR"

# 解析 symlink / 正規化絕對路徑（macOS 的 readlink 沒有 -f，用 python3）
realpath_() { python3 -c 'import os,sys; print(os.path.realpath(sys.argv[1]))' "$1"; }

fail_count=0
pass() { printf '  PASS  %s\n' "$1"; }
fail() { printf '  FAIL  %s\n' "$1"; fail_count=$((fail_count + 1)); }

echo "repo: $REPO_ROOT"
echo "build: $BIN_ABS"

# --- install-hook 模式：把自己複製成 pre-commit hook（內嵌 repo 與 build 路徑） ---
if [ "$INSTALL_HOOK" = 1 ]; then
    [ -n "$GIT_DIR" ] || { echo "error: $REPO_ROOT 不是 git repo"; exit 2; }
    HOOK_DIR="$GIT_DIR/hooks"
    [ -d "$HOOK_DIR" ] || mkdir -p "$HOOK_DIR"
    SCRIPT="$(cd "$(dirname "$0")" && pwd -P)/$(basename "$0")"
    hook_bin="${HOOK_BIN_DIR:-$BIN_DIR}"
    cat > "$HOOK_DIR/pre-commit" <<EOF
#!/bin/bash
# generated by check_build_tracked.sh --install-hook ($(date '+%Y-%m-%d %H:%M'))
# 每次 commit 前驗證 build/bin 的 dylib 與 rpath 都被 git 追蹤 + main⊆dev 包含性
export BIN_DIR='$hook_bin'
exec '$SCRIPT' --repo '$REPO_ROOT'
EOF
    chmod +x "$HOOK_DIR/pre-commit"
    echo "已安裝 pre-commit hook: $HOOK_DIR/pre-commit (BIN_DIR=$hook_bin)"
    exit 0
fi

# ============ 檢查 6：main⊆dev 分支包含性（main 有的 dev 都要有）============
# 放在 build/bin 存在性檢查之前：無論本 repo 有無 build 目錄都要驗分支紀律。
echo "--- 檢查 main⊆dev 包含性（防兩線分岔） ---"
CUR_BRANCH="$(git -C "$REPO_ROOT" branch --show-current 2>/dev/null)"
for ref in refs/heads/main refs/remotes/github0823/main; do
    git -C "$REPO_ROOT" show-ref --verify --quiet "$ref" || continue
    ref_name="${ref#refs/}"
    if [ "$CUR_BRANCH" = "main" ] && [ "$ref" = "refs/heads/main" ]; then
        fail "正在 main 上直接 commit — 這會使 main 領先 dev（違反 main⊆dev）。請改在 dev commit，再 git switch main && git merge --ff-only dev 晉升"
        break
    fi
    if [ -n "$CUR_BRANCH" ] && [ "$CUR_BRANCH" != "dev" ]; then
        pass "非 dev 分支（$CUR_BRANCH）— 跳過 main⊆dev 檢查"
        break
    fi
    if git -C "$REPO_ROOT" merge-base --is-ancestor "$ref" HEAD 2>/dev/null; then
        pass "main⊆dev: $ref_name 已包含於 HEAD"
    else
        fail "dev 缺少 $ref_name 的 commit（main 有的 dev 沒有）。修復：git merge $ref_name 整合後再 commit（需要時先 git fetch github0823）"
    fi
done

# --- build/bin 不存在 ---
if [ ! -d "$BIN_ABS" ]; then
    if [ "${ALLOW_MISSING:-0}" = 1 ]; then
        echo "SKIP  $BIN_DIR 不存在，ALLOW_MISSING=1 → 不擋 commit"
        exit 0
    fi
    echo "SKIP  $BIN_DIR 不存在（本 repo 若無生產 build 屬正常，用 ALLOW_MISSING=1 略過）"
    exit 0
fi

# ============ 檢查 1：build/bin 內每個 *.dylib 都必須被 git 追蹤 ============
echo "--- 檢查 dylib 被追蹤（洞 B） ---"
DYLIBS=()
while IFS= read -r f; do DYLIBS+=("$f"); done < <(find "$BIN_ABS" -maxdepth 1 -name '*.dylib' -type f 2>/dev/null | sort)
if [ "${#DYLIBS[@]}" -eq 0 ]; then
    fail "build/bin 沒有任何 *.dylib"
else
    for f in "${DYLIBS[@]}"; do
        rel="${f#"$REPO_ROOT"/}"
        if git -C "$REPO_ROOT" ls-files --error-unmatch -- "$rel" >/dev/null 2>&1; then
            pass "追蹤 OK: $rel"
        else
            fail "未追蹤 dylib（會被 git 靜默忽略/遺失）: $rel"
        fi
    done
fi

# ============ 檢查 2：必要 dylib 前綴至少要有一個已追蹤的檔案 ============
for prefix in "${REQUIRED_DYLIB[@]}"; do
    found=0
    for f in "${DYLIBS[@]}"; do
        base="$(basename "$f")"
        case "$base" in
            "$prefix"*)
                rel="${f#"$REPO_ROOT"/}"
                if git -C "$REPO_ROOT" ls-files --error-unmatch -- "$rel" >/dev/null 2>&1; then found=1; fi
                ;;
        esac
    done
    if [ "$found" = 1 ]; then
        pass "必要 dylib 前綴已追蹤: $prefix"
    else
        fail "缺少已追蹤的必要 dylib 前綴: $prefix"
    fi
done

# ============ 檢查 3：symlink 必須解析到已追蹤的目標 ============
echo "--- 檢查 symlink 目標被追蹤 ---"
LINKS=()
while IFS= read -r l; do LINKS+=("$l"); done < <(find "$BIN_ABS" -maxdepth 1 -type l 2>/dev/null | sort)
for l in "${LINKS[@]}"; do
    target="$(realpath_ "$l")"
    rel_target="${target#"$REPO_ROOT"/}"
    if [ "$rel_target" = "$target" ]; then
        fail "symlink 指向 repo 外: $l -> $target"
        continue
    fi
    if git -C "$REPO_ROOT" ls-files --error-unmatch -- "$rel_target" >/dev/null 2>&1; then
        pass "symlink 目標已追蹤: $(basename "$l") -> $rel_target"
    else
        fail "symlink 目標未追蹤（洞 B）: $l -> $rel_target"
    fi
done

# ============ 檢查 4：關鍵 exe 存在且被追蹤 ============
echo "--- 檢查關鍵 exe 被追蹤 ---"
for exe in "${REQUIRED_EXES[@]}"; do
    p="$BIN_ABS/$exe"
    if [ ! -x "$p" ]; then
        fail "關鍵 exe 不存在: $exe"
        continue
    fi
    rel="${p#"$REPO_ROOT"/}"
    if git -C "$REPO_ROOT" ls-files --error-unmatch -- "$rel" >/dev/null 2>&1; then
        pass "exe 追蹤 OK: $rel"
    else
        fail "未追蹤 exe: $rel"
    fi
done

# ============ 檢查 5：關鍵 exe 的 @rpath 必須指向本 repo 自己的 build/bin ============
echo "--- 檢查 @rpath（洞 D） ---"
for exe in "${REQUIRED_EXES[@]}"; do
    p="$BIN_ABS/$exe"
    [ -x "$p" ] || continue
    # otool: LC_RPATH 下的 path 行 → 取第 2 欄（絕對路徑）
    rpaths=($(otool -l "$p" 2>/dev/null | awk '/LC_RPATH/{f=1} f && /path /{print $2; f=0}'))
    if [ "${#rpaths[@]}" -eq 0 ]; then
        fail "@rpath 不存在（可能載入不相容 dylib）: $exe"
        continue
    fi
    ok=0
    for rp in "${rpaths[@]}"; do
        rp_real="$(realpath_ "$rp")"
        if [ "$rp_real" = "$BIN_ABS" ]; then ok=1; fi
    done
    if [ "$ok" = 1 ]; then
        pass "@rpath 指向本 repo build/bin: $exe -> ${rpaths[*]}"
    else
        fail "@rpath 被改到別處（洞 D）: $exe -> ${rpaths[*]}（預期 $BIN_ABS）"
    fi
done

# ============ 總結 ============
if [ "$fail_count" -gt 0 ]; then
    echo ""
    echo "FAIL: $fail_count 項未通過。先修好再 commit（關鍵 build 產物不允許 untracked / rpath 錯亂）。"
    exit 1
fi
echo ""
echo "OK: build/bin 的 dylib 與 rpath 追蹤正常，main⊆dev 包含性成立。"
exit 0
